### PR TITLE
Change include order.

### PR DESCRIPTION
**Pull request by LeifAndersen**
Because game_list.hpp doesn't declare the game type at all, it must come after puzzles.hpp.

### CODE REVIEW

**Comment by raisjn** [comment]
can you link the compiler errors this is fixing? 
fwiw, my build is fine. in general, the build here is non-deterministic (due to inode ordering when running `find` to compile the source into one file?). i use the line below (in the Makefile) to create deterministic ordering, it may help you. 

```
SRCS   = $(shell find src/ -type f -name '*.cpp' | sort)
```

**Comment by LeifAndersen** [comment]
@raisjn Sure:

```
$ make
docker run \
	--user 1001:1001 \
	-v "/home/leif/src/remarkable_puzzles:/home/leif/src/remarkable_puzzles" -w "/home/leif/src/remarkable_puzzles" \
	-e ARCH -e BUILD -e BUILD_ROOT -e BUILD_DIR \
	--rm remarkable_puzzles_toolchain:latest \
	make puzzles  -r
arm-linux-gnueabihf-g++ -Wall -I./ -Isrc/ -Ivendor/inih -Ivendor/puzzles -isystem build/debug/ -D"REMARKABLE=1" -pthread -lpthread -g -fdata-sections -ffunction-sections -Wl,--gc-sections -MMD -MP -c -o build/debug/main.o build/debug/main.cpp
In file included from ./src/main.cpp:6,
                 from build/debug/main.cpp:1:
./src/game_list.hpp:4:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game blackbox;
              ^~~~
              time
./src/game_list.hpp:5:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game bridges;
              ^~~~
              time
./src/game_list.hpp:6:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game cube;
              ^~~~
              time
./src/game_list.hpp:7:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game galaxies;
              ^~~~
              time
./src/game_list.hpp:8:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game inertia;
              ^~~~
              time
./src/game_list.hpp:9:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game lightup;
              ^~~~
              time
./src/game_list.hpp:10:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game mines;
              ^~~~
              time
./src/game_list.hpp:11:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game net;
              ^~~~
              time
./src/game_list.hpp:12:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game pearl;
              ^~~~
              time
./src/game_list.hpp:13:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game pegs;
              ^~~~
              time
./src/game_list.hpp:14:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game samegame;
              ^~~~
              time
./src/game_list.hpp:15:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game slant;
              ^~~~
              time
./src/game_list.hpp:16:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game tents;
              ^~~~
              time
./src/game_list.hpp:17:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game tracks;
              ^~~~
              time
./src/game_list.hpp:18:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game unruly;
              ^~~~
              time
./src/game_list.hpp:19:14: error: 'game' does not name a type; did you mean 'time'?
 extern const game untangle;
              ^~~~
              time
./src/game_list.hpp:21:14: error: 'game' does not name a type; did you mean 'time'?
 static const game * GAME_LIST[] = {
              ^~~~
              time
In file included from build/debug/main.cpp:6:
./src/ui/chooser_scene.cpp: In constructor 'ChooserScene::ChooserScene()':
./src/ui/chooser_scene.cpp:89:21: error: 'GAME_LIST' was not declared in this scope
     for (auto * g : GAME_LIST) {
                     ^~~~~~~~~
./src/ui/chooser_scene.cpp:89:21: note: suggested alternative: 'KEY_LIST'
     for (auto * g : GAME_LIST) {
                     ^~~~~~~~~
                     KEY_LIST
make: *** [Makefile:70: build/debug/main.o] Error 1
Makefile:92: recipe for target 'docker' failed
make: *** [docker] Error 2
```

This is on Ubuntu 18.04, with arm-linux-gnueabihf-g++ 7.5

Maybe I don't have the right build environment installed?

**Comment by mrichards42** [comment]
Good catch! Every cpp file should be able to compile on its own, but since I have to make a single cpp file in the end, I've probably been sloppy like this in a few other places (raisjn caught a missing sstream include yesterday for instance).

https://github.com/mrichards42/remarkable_puzzles/commit/838c4301f5e6a8ed7a3edcb6ab81d4408ab0d3b1 should fix this, by including puzzles.hpp in game_list.hpp. I also took the opportunity to get rid of some duplication in that file.
